#!/usr/bin/env bash
export PATH=/home/vanessa/arm-bins/cross-compilation/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH
export LDFLAGS=/home/vanessa/arm-bins/cross-compilation/zlib/
cargo build --release
cargo build --bin sniff --target=x86_64-pc-windows-gnu --release
cargo build --bin sniff --target=arm-unknown-linux-gnueabihf --release
